config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/new', to: 'users#new', as: 'newuser'

  get '/:user/:name', to: 'users#show'

  # post '/:user', to: 'users_controller#new_post'
  post '/create', to: 'users#create'

  get '/fuckoff', to: 'users#fuck'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def new
  end

  def user
  end

  def fuck
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
     @user = User.new
     @user.username = params["username"]
     @user.save

     if @user.save
       redirect_to "/"
     else
       redirect_to "/fuckoff"
   end
 end

  def show
    @name = params[:username]
  end

  def fuck
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Bienvenue sur ma page d'accueil (heroku version)</h1>
<p>YOOOOOOOOOOOOOOOOOo</p>

<a href="<%= newuser_path %>">new user </a>

app/views/users/fuck.html.erb
<h1>get the fuck out my site </h1>

app/views/users/new.html.erb
<h1>Bienvenue sur NEWWWWWWWWWWWWWW</h1>
<p>YOOOOOOOOOOOOOOOOOo</p>
<form action="create" method= "post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="username"> <br>
  <hr>
  <input type="text" name="bio">
  <input type ="submit" name="Envoyer">
</form>

app/views/users/show.html.erb
<h1>Bienvenue username ! Voici ta bio trop cool : bio</h1>
<p><%= @name %></p>